---
site_name: Material for MkDocs demo
# site_url: https://squidfunk.github.io/mkdocs-material/
site_author: mafrosis
site_description: >-
  Playground built ontop of https://squidfunk.github.io/mkdocs-material

repo_name: mafrosis/mkdocs
repo_url: https://github.com/mafrosis/mkdocs

copyright: Hello from mafrosis

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - tabs

nav:
  - Home: index.md
  - How to use:
      - Playground: howto/playground.md
      - Contribution: howto/contribution.md

# plugins execute in order, minify should come last
plugins:
  - search
  - git-revision-date-localized
  - drawio-exporter:
      cache_dir: .drawio-exporter
      drawio_args:
        - --no-sandbox
  - minify:
      minify_html: true

markdown_extensions:
  - markdown.extensions.attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
